.\" See LICENSE file for copyright and license details.
.TH DWMSTATUS 1 "September 2014" "dwmstatus-2.2"
.SH NAME
.B dwmstatus
\- status indicator
.SH SYNOPSIS
.B dwmstatus
\fB\-i\fP \fIdevname\fP
[\fB\-m\fP \fImaildir\fP]
.SH DESCRIPTION
.BI dwmstatus
is a status indicator for the X root window.
.SH OPTIONS
.TP
.BR "\-i \fIdevname\fP", " \-\-interface \fIdevname\fP"
indicate the name of the network device from which to read information
.TP
.BR "\-m \fImaildir\fP\fN", " \-\-maildir \fImaildir\fP"
indicate the directory of a Maildir
